### ISSUE TITLE
Unrecognized image format for pics

### ISSUE THREAD

**Issue by bwsinger** [ungive/image-updater#1]
I tried both the Windows and Mac versions of the downloader for YGOPro1 but in both cases, the pics (the card images) have a *.png extension but are not recognized file formats. When downloading there are no thumbnails and there are no thumbnails when downloaded due to the formatting issue. The field spell images download fine, however.
![downloader-problem](https://cloud.githubusercontent.com/assets/16724046/26455485/3cecc478-411f-11e7-8bae-aeb5cf0230fc.gif)
![downloader2](https://cloud.githubusercontent.com/assets/16724046/26455500/47d06bd8-411f-11e7-83c6-d288efeba02e.png)

**Comment by ungive** [comment]
The ImageUpdater creates the files and pipes the data that is downloaded.
At the moment though, the links are outdated and do not point to the correct resources which results in either failed downloads or (like in this case) garbage data inside the file that is then considered damaged.
The links will be updated soon.

**Comment by bwsinger** [comment]
That's great to hear! I'll wait for a while before trying to re-update.

**Comment by ungive** [comment]
The issue is fixed.
