### ISSUE TITLE
Not working in Windows 8.1

### ISSUE THREAD

**Issue by Vorpalblada** [ungive/image-updater#2]
![screenshot 1](https://cloud.githubusercontent.com/assets/10861651/26559993/574095cc-44dd-11e7-8377-b0d3cec46997.png)

**Comment by BeyondTheHorizon** [comment]
I'm having the same error. Somebody please help.

**Comment by ungive** [comment]
This updater is now officially deprecated and not supported anymore. You should have been supplied with an alternative program, though if not, feel free to contact me.
